version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    # Limit the number of open pull requests for npm
    open-pull-requests-limit: 5
    # Add labels to categorize updates (removed invalid "npm" label)
    labels:
      - "dependencies"
    # Cooldown configuration to reduce noise (2025 feature)
    # Wait X days after a new version is released before creating PR
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 3
      semver-major-days: 7
    # Group minor and patch updates together to reduce PR noise
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Keep major updates separate for careful review
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    # Allow specific dependency types and ignore others for better control
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-types: ["security"]
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    # Limit the number of open pull requests for GitHub Actions
    open-pull-requests-limit: 2
    # Add labels to categorize updates
    labels:
      - "dependencies"
      - "github-actions"
    # Cooldown for GitHub Actions (less conservative than npm)
    cooldown:
      semver-patch-days: 1
      semver-minor-days: 1
      semver-major-days: 3
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
