name: Basic Workflow

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs at the end of every day (midnight UTC)

jobs:
  simple-task:
    runs-on: ubuntu-latest
    steps:
      - name: Create new booking
        env:
          DESKBIRD_ACCESS_TOKEN: ${{ secrets.DESKBIRD_ACCESS_TOKEN }}
        run: ./scripts/new_booking.sh