name: Basic Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * *'  # Runs at the end of every day (midnight UTC)

jobs:
  simple-task:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo command
        run: echo 1